### ISSUE TITLE
Citing data version number from preprocessData packages

### ISSUE THREAD

**Issue by wfulp** [RGLab/preprocessData#4]
What is the best way to include the data version number into the citation of a package from preprocessData? I could do this manually in the knitr code, but since this would be something we would want to include in reports whenever using a data package created frompreprocessData, is there a way to automatically add it? When I use the citation function or the repmis::LoadandCite function on a package from preprocessData I get the package version number, but not the data version number.

**Comment by gfinak** [comment]
With preprocessData loaded, you can type
packageVersion(“AUP567”)
To get the packageVersion 
And dataVersion(“AUP567”) to get the data version. 

Greg

From:  Jimmy Fulp
Reply-To:  RGLab/preprocessData
Date:  Monday, June 15, 2015 at 11:37 AM
To:  RGLab/preprocessData
Subject:  [preprocessData] Citing data version number from preprocessData packages (#4)


What is the best way to include the data version number into the citation of a package from preprocessData? I could do this manually in the knitr code, but since this would be something we would want to include in reports whenever using a data package created frompreprocessData, is there a way to automatically add it? When I use the citation function or the repmis::LoadandCite function on a package from preprocessData I get the package version number, but not the data version number.
